[build.environment]
  HMS_ENDPOINT='wss://prod-in.100ms.live'
  TOKEN_ENDPOINT='https://ms-services-djl9mbcew00y.runkit.sh/'

  FIREBASE_API_KEY=<firebaseConfig.apiKey>
  FIREBASE_AUTH_DOMAIN=<firebaseConfig.authDomain>
  FIREBASE_DATABASE_URL=<firebaseConfig.databaseURL>
  FIREBASE_PROJECT_ID=<firebaseConfig.projectId>
  FIREBASE_STORAGE_BUCKET=<firebaseConfig.storageBucket>
  FIREBASE_MESSAGING_ID=<firebaseConfig.messagingSenderId>
  FIREBASE_APP_ID=<firebaseConfig.appId>
  FIREBASE_MEASUREMENT_ID=<firebaseConfig.measurementId>
